name: '🚀 Deploy to AWS'

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true
      CLIENT_ID:
        required: true

jobs:
  deploy:
    timeout-minutes: 5
    name: '🚀 Deploy to AWS'
    env:
      TOKEN: ${{ secrets.TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install the dependencies
      uses: Borales/actions-yarn@v4
      with:
        cmd: install
    - name: (TESTING) Update the slash commands
      uses: Borales/actions-yarn@v4
      with:
        cmd: register

   