name: '🤠 Build and Test'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: '🤠 Build and Test'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup Checkout'
      uses: actions/checkout@v3
    - name: 'Setup Node.js 16'
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install the dependencies
      uses: Borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build the bot
      uses: Borales/actions-yarn@v4
      with:
        cmd: build
   