# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update Slash commands

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install the dependencies
      uses: Borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build the bot
      uses: Borales/actions-yarn@v4
      with:
        cmd: build
    - name: Update the slash commands
      uses: Borales/actions-yarn@v4
      with:
        cmd: prestart