name: '🛠 Update Slash commands'

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 5
    name: '📝 Register Slash commands'
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install the dependencies
      uses: Borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build the bot
      uses: Borales/actions-yarn@v4
      with:
        cmd: build
    - name: Update the slash commands
      uses: Borales/actions-yarn@v4
      with:
        cmd: register
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: production-${{ github.sha }}
        retention-days: 1
        path: |
          dist
          package.json

  call-deploy:
    name: "📡 Deploy workflow"
    needs: build
    uses: ezegatica/bot/.github/workflows/deploy.yml@main
    with:
      artifact-name: production-${{ github.sha }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}